// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
)

type Trip struct {
	TripID    int32
	Name      string
	CreatedAt sql.NullTime
}

type Tripitem struct {
	TripItemID int32
	Name       string
	CreatedAt  sql.NullTime
	TripListID int32
	IsPacked   sql.NullBool
}

type Triplist struct {
	TripListID int32
	Name       string
	CreatedAt  sql.NullTime
	UserID     int32
	TripID     int32
}

type User struct {
	UserID int32
	Email  string
}
