-- POSTGRES
-- CREATE TABLE/SCHEMA
CREATE TABLE "User" (
    user_id SERIAL PRIMARY KEY,
    email TEXT NOT NULL
);


CREATE TABLE Trip (
    trip_id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TripList (
    trip_list_id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id INT NOT NULL REFERENCES "User" ON DELETE CASCADE,
    trip_id INT NOT NULL REFERENCES Trip ON DELETE CASCADE
);

CREATE TABLE TripItem (
    trip_item_id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    trip_list_id INT NOT NULL REFERENCES TripList ON DELETE CASCADE,
    is_packed BOOLEAN DEFAULT FALSE
);

